### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by koen-dejonghe** [ctongfei/JTorch#1]
Hi,

I have a very simple program:
```
package mytorch
import jtorch.cpu._
object MyTorch extends App {
  println(System.getProperty("java.library.path"))
  val x = THJNI.new_THFloatTensor()
  println(x)
}
```
but I'm unable to run it because of a java.lang.UnsatisfiedLinkError.
I followed your instructions for building, and I include libjnith.dylib, as well as the pyTorch dylibs in java.library.path.
Not sure what I'm doing wrong.
Thank you.
Kind regards, 

Koen.

**Comment by ctongfei** [comment]
Hello! 
This is a project in progress and it is not currently ready for use. I can make the CPU version run a few weeks ago but probably Torch has updated its C code so there might be some issues. 
Sorry but I'm not working on this right now. If you can debug it feel free to start a PR.

**Comment by ctongfei** [comment]
Should be fixed now.
