### ISSUE TITLE
Is there any update for pytorch's ATen?

### ISSUE THREAD

**Issue by Teaonly** [ctongfei/JTorch#2]
Now pytorch basic library is based on Aten, do you have plan to support ATen. https://github.com/zdevito/ATen

**Comment by ctongfei** [comment]
Yes I plan to do that later. I'm quite busy now so forgive me for not updating quickly

**Comment by Teaonly** [comment]
I have tried a same way like yours to compiling ATen to jni library. 
Some functions will be optimized in the ATen's output library, so there is no linked point for jni libraray ( use gcc -E ), just removing them from generated header file manually. 

https://github.com/Teaonly/clj-torch

**Comment by ctongfei** [comment]
Probably no -- C only Torch is much easier to work with.
