### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bitstormGER** [ctongfei/JTorch#4]
I was just about writing a similar wrapper when I found this project - first of all many thanks for sharing your work!
It would be great if you could state a licences for the project (sorry  if I overlooked something) so it is clear if and how this can be reused.

**Comment by ctongfei** [comment]
thanks for the interest! I plan to work on this in the near future (very busy right now). This is going to be used as backend for my typesafe deep learning engine (https://github.com/ctongfei/nexus) and will consolidate on PyTorch 0.4.

Now licensed under MIT.
